### ISSUE TITLE
Followed the steps outlined in Readme.md, but it doesn't work

### ISSUE THREAD

**Issue by gmanish** [rafis/schema-extended#1]
I need to create a table where the pk will be a uuid. It seems like this package is just what I need. I tried all the steps listed in Readme.md, but I get the following error:

```
 [ErrorException]                         
  Class 'SchemaExtended\Schema' not found
```

Following is my migration file that tries to create a table with a binary(16) primary key column:

```
  public function up()
  {
      Schema::create('test_binary', function (Blueprint $table) {
          $table->binary('uuid', 16)->primary();
          $table->timestamps();
      });
  }
```

I do not see the folder `SchemaExtended` on my source code folder either. Where is it supposed to install?

Sorry about bothering you with this request. There didn't seem any other way of getting in touch with you.

**Comment by rafis** [comment]
After you add something to `composer.json`, you need to run 

```
composer install
```

It should install package to `vendor/rafis/schema-extended` and update composer's autoloader so it can find `SchemaExtended\Schema` class.
